# Generated by Django 2.1.7 on 2019-05-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20190520_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(max_length=100),
        ),
    ]
